-- ops_documents: tracks PDFs generated by agents (proposals, letters, general docs)
-- TTL: 30 days from creation, reset to now+30 on any access/download

create table if not exists ops_documents (
  id               uuid primary key default gen_random_uuid(),
  agent_id         uuid not null references voice_agents(id) on delete cascade,
  title            text not null,
  filename         text not null,
  storage_path     text not null,
  template_type    text not null default 'general', -- 'general' | 'proposal' | 'letter'
  created_at       timestamptz not null default now(),
  last_accessed_at timestamptz,
  expires_at       timestamptz not null default (now() + interval '30 days')
);

create index if not exists ops_documents_agent_id_idx on ops_documents(agent_id);
create index if not exists ops_documents_expires_at_idx on ops_documents(expires_at);

-- RLS: only the service role (admin client) can access
alter table ops_documents enable row level security;
create policy "service role only" on ops_documents using (false);
