// Lista curada de ladas MX + US usada tanto por el registro como por el portal
// (add-employee, activate-voice). Fuente única para no duplicar el catálogo.
// Actualizado desde src/app/registro/page.tsx.

export type LadaCountry = 'mx' | 'us';

export interface CityLada { label: string; lada: string }

export const CITIES_MX: CityLada[] = [
  { label: 'CDMX / Ciudad de México',  lada: '55'  },
  { label: 'Monterrey, NL',            lada: '81'  },
  { label: 'Guadalajara, JAL',         lada: '33'  },
  { label: 'Puebla, PUE',              lada: '222' },
  { label: 'Tijuana, BC',              lada: '664' },
  { label: 'León, GTO',                lada: '477' },
  { label: 'Querétaro, QRO',           lada: '442' },
  { label: 'Cancún, QR',               lada: '998' },
  { label: 'Mérida, YUC',              lada: '999' },
  { label: 'Hermosillo, SON',          lada: '662' },
  { label: 'Chihuahua, CHIH',          lada: '614' },
  { label: 'Juárez, CHIH',             lada: '656' },
  { label: 'San Luis Potosí, SLP',     lada: '444' },
  { label: 'Aguascalientes, AGS',      lada: '449' },
  { label: 'Morelia, MICH',            lada: '443' },
  { label: 'Torreón, COAH',            lada: '871' },
  { label: 'Saltillo, COAH',           lada: '844' },
  { label: 'Culiacán, SIN',            lada: '667' },
  { label: 'Mazatlán, SIN',            lada: '669' },
  { label: 'Veracruz, VER',            lada: '229' },
  { label: 'Xalapa, VER',              lada: '228' },
  { label: 'Oaxaca, OAX',              lada: '951' },
  { label: 'Acapulco, GRO',            lada: '744' },
  { label: 'Villahermosa, TAB',        lada: '993' },
  { label: 'Tuxtla Gutiérrez, CHIS',   lada: '961' },
  { label: 'San Cristóbal, CHIS',      lada: '967' },
  { label: 'Cuernavaca, MOR',          lada: '777' },
  { label: 'Toluca, MEX',              lada: '722' },
  { label: 'Durango, DUR',             lada: '618' },
  { label: 'Zacatecas, ZAC',           lada: '492' },
  { label: 'Tepic, NAY',               lada: '311' },
  { label: 'Colima, COL',              lada: '312' },
  { label: 'Pachuca, HGO',             lada: '771' },
  { label: 'Campeche, CAMP',           lada: '981' },
  { label: 'Chetumal, QR',             lada: '983' },
  { label: 'Ensenada, BC',             lada: '646' },
  { label: 'Los Cabos, BCS',           lada: '624' },
];

export const CITIES_US: CityLada[] = [
  { label: 'Atlanta, GA',              lada: '404' },
  { label: 'Austin, TX',               lada: '512' },
  { label: 'Baltimore, MD',            lada: '410' },
  { label: 'Boston, MA',               lada: '617' },
  { label: 'Charlotte, NC',            lada: '704' },
  { label: 'Chicago, IL',              lada: '312' },
  { label: 'Cleveland, OH',            lada: '216' },
  { label: 'Dallas, TX',               lada: '214' },
  { label: 'Denver, CO',               lada: '303' },
  { label: 'Detroit, MI',              lada: '313' },
  { label: 'El Paso, TX',              lada: '915' },
  { label: 'Houston, TX',              lada: '713' },
  { label: 'Indianapolis, IN',         lada: '317' },
  { label: 'Jacksonville, FL',         lada: '904' },
  { label: 'Kansas City, MO',          lada: '816' },
  { label: 'Las Vegas, NV',            lada: '702' },
  { label: 'Los Angeles, CA',          lada: '213' },
  { label: 'Louisville, KY',           lada: '502' },
  { label: 'Memphis, TN',              lada: '901' },
  { label: 'Miami, FL',                lada: '305' },
  { label: 'Milwaukee, WI',            lada: '414' },
  { label: 'Minneapolis, MN',          lada: '612' },
  { label: 'Nashville, TN',            lada: '615' },
  { label: 'New York, NY',             lada: '212' },
  { label: 'Oklahoma City, OK',        lada: '405' },
  { label: 'Orlando, FL',              lada: '407' },
  { label: 'Philadelphia, PA',         lada: '215' },
  { label: 'Phoenix, AZ',              lada: '602' },
  { label: 'Portland, OR',             lada: '503' },
  { label: 'Raleigh, NC',              lada: '919' },
  { label: 'Sacramento, CA',           lada: '916' },
  { label: 'Salt Lake City, UT',       lada: '801' },
  { label: 'San Antonio, TX',          lada: '210' },
  { label: 'San Diego, CA',            lada: '619' },
  { label: 'San Francisco, CA',        lada: '415' },
  { label: 'San Jose, CA',             lada: '408' },
  { label: 'Seattle, WA',              lada: '206' },
  { label: 'Tampa, FL',                lada: '813' },
  { label: 'Tucson, AZ',               lada: '520' },
  { label: 'Virginia Beach, VA',       lada: '757' },
  { label: 'Washington, DC',           lada: '202' },
];

export const CITIES_BY_COUNTRY: Record<LadaCountry, CityLada[]> = {
  mx: [...CITIES_MX].sort((a, b) => Number(a.lada) - Number(b.lada)),
  us: [...CITIES_US].sort((a, b) => Number(a.lada) - Number(b.lada)),
};
