/**
 * round-trip.harness.ts — Harness de round-trip XML para el adaptador CONTPAQi.
 *
 * Carga un XML real de CONTPAQi (post-timbrado), extrae los campos que controla
 * el adapter, genera el XML de importacion con buildImportXml, y compara
 * campo a campo. Devuelve un DiffReport con diffs estructurados y legibles.
 *
 * Campos ignorados (generados por el PAC/SAT al timbrar, no por nuestro adapter):
 *   - UUID (FolioFiscal / NoCertificadoSAT del SAT)
 *   - Sello, SelloSAT, SelloCFD
 *   - FechaTimbrado
 *   - NoCertificadoSAT (del PAC)
 *   - NoCertificado (del emisor — lo asigna CONTPAQi al timbrar)
 *   - Certificado (cadena del certificado del emisor)
 *   - RfcProvCertif
 *   - Folio (numero de folio asignado por CONTPAQi)
 *   - Fecha (timestamp completo con hora — nosotros solo manejamos fecha YYYY-MM-DD)
 *   - TipoDeComprobante, Exportacion (valores fijos de CFDI; no los genera nuestro XML ADD)
 *   - Version (del cfdi:Comprobante)
 *   - Nombre del Emisor y Receptor (en el ADD nosotros solo ponemos RFC)
 *   - DomicilioFiscalReceptor, RegimenFiscalReceptor (del receptor — no en nuestro ADD)
 *   - ClaveProdServ, ClaveUnidad, Unidad, Descripcion, ObjetoImp (catalogo SAT del producto — no en nuestro ADD)
 *   - xmlns y xsi (namespaces del CFDI — nuestro ADD usa un namespace diferente)
 *
 * Uso:
 *   const report = runRoundTrip('path/to/real.contpaqi.xml', 'path/to/input.json');
 *   console.log(formatDiffReport(report));
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { XMLParser } from 'fast-xml-parser';
import { buildImportXml, type XmlImportConfig } from '../xml-import';
import type { BillingInvoice } from '@/lib/billing/adapter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FieldDiff {
  field: string;
  ourValue: string | null;
  theirValue: string | null;
  /** mismatch: both present but different; missing_in_ours: in theirs but not ours; extra_in_ours: in ours but not theirs */
  status: 'mismatch' | 'missing_in_ours' | 'extra_in_ours';
}

export interface DiffReport {
  /** Basename of the fixture pair (e.g. 'dummy') */
  fixture: string;
  /** true if diffs is empty */
  passed: boolean;
  diffs: FieldDiff[];
  /** List of field names intentionally skipped */
  ignoredFields: string[];
  /** One-line human summary */
  summary: string;
}

// ---------------------------------------------------------------------------
// Input shape
// ---------------------------------------------------------------------------

interface AdapterInput {
  invoice: BillingInvoice;
  config: XmlImportConfig;
}

// ---------------------------------------------------------------------------
// Fields that are generated by the PAC/SAT at timbrado time.
// We never produce them in our XML ADD, so differences are expected and OK.
// ---------------------------------------------------------------------------

const IGNORED_FIELDS = new Set<string>([
  'UUID',
  'FolioFiscal',
  'Sello',
  'SelloSAT',
  'SelloCFD',
  'FechaTimbrado',
  'NoCertificadoSAT',
  'NoCertificado',
  'Certificado',
  'RfcProvCertif',
  'Folio',
  'Fecha', // CFDI uses datetime; our ADD uses date only
  'TipoDeComprobante',
  'Exportacion',
  'Version', // cfdi:Comprobante Version="4.0" vs our ADD xmlns
  'Nombre', // Emisor/Receptor name — not in our ADD
  'DomicilioFiscalReceptor',
  'RegimenFiscalReceptor',
  'ClaveProdServ',
  'ClaveUnidad',
  'Unidad',
  'Descripcion',
  'ObjetoImp',
  'xsi:schemaLocation',
]);

// ---------------------------------------------------------------------------
// CFDI XML parser
// ---------------------------------------------------------------------------

interface CfdiEncabezado {
  RfcEmisor: string;
  RfcReceptor: string;
  UsoCFDI: string;
  MetodoPago: string;
  FormaPago: string;
  Moneda: string;
  LugarExpedicion: string;
  Subtotal: string;
  Total: string;
  Serie: string;
}

interface CfdiMovimiento {
  CodigoProducto: string;
  Cantidad: string;
  PrecioUnitario: string;
  Importe: string;
  IvaTasa: string;
}

/**
 * Extracts the fields that our XML ADD controls from a real CFDI 4.0 XML
 * exported from CONTPAQi.
 *
 * CONTPAQi CFDI uses the cfdi namespace; our ADD uses a proprietary namespace.
 * This function maps CFDI field names to our ADD field names so they can be
 * compared apples-to-apples.
 */
function parseCfdiXml(xmlContent: string): {
  encabezado: CfdiEncabezado;
  movimientos: CfdiMovimiento[];
} {
  const parser = new XMLParser({
    ignoreAttributes: false,
    attributeNamePrefix: '@_',
    removeNSPrefix: true, // strips cfdi: and tfd: prefixes
    parseAttributeValue: false, // keep all attribute values as strings (avoids "03" -> 3)
    parseTagValue: false, // keep all text node values as strings
  });

  const parsed = parser.parse(xmlContent) as Record<string, unknown>;

  // After removeNSPrefix, the root is 'Comprobante'
  const comprobante = parsed['Comprobante'] as Record<string, unknown>;
  if (!comprobante) {
    throw new Error(
      'round-trip.harness: parseCfdiXml — could not find <cfdi:Comprobante> (or <Comprobante>) root element',
    );
  }

  const emisorNode = comprobante['Emisor'] as Record<string, unknown>;
  const receptorNode = comprobante['Receptor'] as Record<string, unknown>;
  const conceptosNode = comprobante['Conceptos'] as Record<string, unknown>;

  if (!emisorNode || !receptorNode || !conceptosNode) {
    throw new Error(
      'round-trip.harness: parseCfdiXml — missing Emisor, Receptor, or Conceptos node',
    );
  }

  const encabezado: CfdiEncabezado = {
    RfcEmisor: String(emisorNode['@_Rfc'] ?? ''),
    RfcReceptor: String(receptorNode['@_Rfc'] ?? ''),
    UsoCFDI: String(receptorNode['@_UsoCFDI'] ?? ''),
    MetodoPago: String(comprobante['@_MetodoPago'] ?? ''),
    FormaPago: String(comprobante['@_FormaPago'] ?? ''),
    Moneda: String(comprobante['@_Moneda'] ?? ''),
    LugarExpedicion: String(comprobante['@_LugarExpedicion'] ?? ''),
    Subtotal: String(comprobante['@_SubTotal'] ?? ''),
    Total: String(comprobante['@_Total'] ?? ''),
    Serie: String(comprobante['@_Serie'] ?? ''),
  };

  // Conceptos can be a single object or an array (fast-xml-parser behavior)
  const rawConceptos = conceptosNode['Concepto'];
  const conceptoList: Record<string, unknown>[] = Array.isArray(rawConceptos)
    ? (rawConceptos as Record<string, unknown>[])
    : [rawConceptos as Record<string, unknown>];

  const movimientos: CfdiMovimiento[] = conceptoList.map((c) => ({
    CodigoProducto: String(c['@_NoIdentificacion'] ?? ''),
    Cantidad: String(c['@_Cantidad'] ?? ''),
    PrecioUnitario: String(c['@_ValorUnitario'] ?? ''),
    Importe: String(c['@_Importe'] ?? ''),
    // CFDI does not have IvaTasa per-line in the Concepto node — it's in
    // cfdi:Impuestos/cfdi:Traslados. For this round-trip we compare the
    // value our adapter produced, accepting that CFDI structures IVA differently.
    // IvaTasa is compared only at our ADD level (parsed from our generated XML).
    IvaTasa: '', // intentionally empty — parsed from our side only
  }));

  return { encabezado, movimientos };
}

// ---------------------------------------------------------------------------
// Our ADD XML parser
// ---------------------------------------------------------------------------

/**
 * Parses the XML generated by buildImportXml into the same shape as
 * parseCfdiXml for direct comparison.
 */
function parseOurXml(xmlContent: string): {
  encabezado: CfdiEncabezado;
  movimientos: CfdiMovimiento[];
} {
  const parser = new XMLParser({
    ignoreAttributes: false,
    attributeNamePrefix: '@_',
    removeNSPrefix: true,
    parseTagValue: false, // keep all text node values as strings (avoids "03" -> 3)
  });

  const parsed = parser.parse(xmlContent) as Record<string, unknown>;
  const documentos = parsed['Documentos'] as Record<string, unknown>;
  if (!documentos) {
    throw new Error('round-trip.harness: parseOurXml — could not find <Documentos> root element');
  }

  const rawDoc = documentos['Documento'];
  // Take the first document for comparison (single-invoice fixture)
  const documento = (
    Array.isArray(rawDoc) ? (rawDoc as Record<string, unknown>[])[0] : rawDoc
  ) as Record<string, unknown>;

  const enc = documento['Encabezado'] as Record<string, unknown>;
  const movNode = documento['Movimientos'] as Record<string, unknown>;

  const encabezado: CfdiEncabezado = {
    RfcEmisor: String(enc['RfcEmisor'] ?? ''),
    RfcReceptor: String(enc['RfcReceptor'] ?? ''),
    UsoCFDI: String(enc['UsoCFDI'] ?? ''),
    MetodoPago: String(enc['MetodoPago'] ?? ''),
    FormaPago: String(enc['FormaPago'] ?? ''),
    Moneda: String(enc['Moneda'] ?? ''),
    LugarExpedicion: String(enc['LugarExpedicion'] ?? ''),
    Subtotal: String(enc['Subtotal'] ?? ''),
    Total: String(enc['Total'] ?? ''),
    Serie: String(enc['Serie'] ?? ''),
  };

  const rawMovimientos = movNode['Movimiento'];
  const movimientoList: Record<string, unknown>[] = Array.isArray(rawMovimientos)
    ? (rawMovimientos as Record<string, unknown>[])
    : [rawMovimientos as Record<string, unknown>];

  const movimientos: CfdiMovimiento[] = movimientoList.map((m) => ({
    CodigoProducto: String(m['CodigoProducto'] ?? ''),
    Cantidad: String(m['Cantidad'] ?? ''),
    PrecioUnitario: String(m['PrecioUnitario'] ?? ''),
    Importe: String(m['Importe'] ?? ''),
    IvaTasa: String(m['IvaTasa'] ?? ''),
  }));

  return { encabezado, movimientos };
}

// ---------------------------------------------------------------------------
// Field comparison
// ---------------------------------------------------------------------------

/**
 * Normalizes a monetary string for comparison: "90.00" == "90.0" == "90".
 * Returns the string as-is if it cannot be parsed as a number.
 */
function normalizeMoney(val: string): string {
  const n = parseFloat(val);
  if (isNaN(n)) return val.trim();
  return n.toFixed(2);
}

/**
 * Normalizes a quantity string (integer or decimal).
 */
function normalizeQty(val: string): string {
  const n = parseFloat(val);
  if (isNaN(n)) return val.trim();
  // Quantities may be integer (5) or decimal (5.0) — normalize to plain number
  return String(n);
}

function compareEncabezado(ours: CfdiEncabezado, theirs: CfdiEncabezado): FieldDiff[] {
  const diffs: FieldDiff[] = [];

  const moneyFields = new Set(['Subtotal', 'Total']);
  const fields = Object.keys(ours) as (keyof CfdiEncabezado)[];

  for (const field of fields) {
    if (IGNORED_FIELDS.has(field)) continue;

    const ourVal = ours[field] ?? '';
    const theirVal = theirs[field] ?? '';

    const ourNorm = moneyFields.has(field) ? normalizeMoney(ourVal) : ourVal.trim();
    const theirNorm = moneyFields.has(field) ? normalizeMoney(theirVal) : theirVal.trim();

    if (ourNorm !== theirNorm) {
      diffs.push({
        field: `Encabezado.${field}`,
        ourValue: ourNorm || null,
        theirValue: theirNorm || null,
        status:
          ourNorm && !theirNorm
            ? 'extra_in_ours'
            : !ourNorm && theirNorm
              ? 'missing_in_ours'
              : 'mismatch',
      });
    }
  }

  return diffs;
}

function compareMovimientos(ours: CfdiMovimiento[], theirs: CfdiMovimiento[]): FieldDiff[] {
  const diffs: FieldDiff[] = [];

  const maxLen = Math.max(ours.length, theirs.length);
  for (let i = 0; i < maxLen; i++) {
    const o = ours[i];
    const t = theirs[i];

    if (!o) {
      diffs.push({
        field: `Movimiento[${i}]`,
        ourValue: null,
        theirValue: JSON.stringify(t),
        status: 'missing_in_ours',
      });
      continue;
    }
    if (!t) {
      diffs.push({
        field: `Movimiento[${i}]`,
        ourValue: JSON.stringify(o),
        theirValue: null,
        status: 'extra_in_ours',
      });
      continue;
    }

    const moneyFields = new Set<keyof CfdiMovimiento>(['PrecioUnitario', 'Importe']);
    const qtyFields = new Set<keyof CfdiMovimiento>(['Cantidad']);
    const fields = Object.keys(o) as (keyof CfdiMovimiento)[];

    for (const field of fields) {
      // IvaTasa from CFDI side is intentionally empty (different structure)
      if (field === 'IvaTasa' && !t[field]) continue;

      const ourVal = o[field] ?? '';
      const theirVal = t[field] ?? '';

      const ourNorm = moneyFields.has(field)
        ? normalizeMoney(ourVal)
        : qtyFields.has(field)
          ? normalizeQty(ourVal)
          : ourVal.trim();
      const theirNorm = moneyFields.has(field)
        ? normalizeMoney(theirVal)
        : qtyFields.has(field)
          ? normalizeQty(theirVal)
          : theirVal.trim();

      if (ourNorm !== theirNorm) {
        diffs.push({
          field: `Movimiento[${i}].${field}`,
          ourValue: ourNorm || null,
          theirValue: theirNorm || null,
          status:
            ourNorm && !theirNorm
              ? 'extra_in_ours'
              : !ourNorm && theirNorm
                ? 'missing_in_ours'
                : 'mismatch',
        });
      }
    }
  }

  return diffs;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Runs a single round-trip comparison between a real CFDI XML from CONTPAQi
 * and the XML our adapter would have generated for the same transaction.
 *
 * @param originalXmlPath  Absolute or relative path to the real CFDI XML from CONTPAQi.
 * @param adapterInputPath Absolute or relative path to the adapter input JSON
 *                         ({ invoice: BillingInvoice, config: XmlImportConfig }).
 * @returns DiffReport with structured diffs and a human-readable summary.
 */
export function runRoundTrip(originalXmlPath: string, adapterInputPath: string): DiffReport {
  const fixture = path.basename(adapterInputPath, '.input.json');

  const originalXml = fs.readFileSync(originalXmlPath, 'utf8');
  const adapterInputRaw = fs.readFileSync(adapterInputPath, 'utf8');
  const adapterInput = JSON.parse(adapterInputRaw) as AdapterInput;

  // Build our XML
  const ourXml = buildImportXml([adapterInput.invoice], adapterInput.config);

  // Parse both sides
  const cfdi = parseCfdiXml(originalXml);
  const ours = parseOurXml(ourXml);

  // Compare
  const diffs: FieldDiff[] = [
    ...compareEncabezado(ours.encabezado, cfdi.encabezado),
    ...compareMovimientos(ours.movimientos, cfdi.movimientos),
  ];

  const passed = diffs.length === 0;
  const summary = passed
    ? `PASS — ${fixture}: all ${Object.keys(ours.encabezado).length + ours.movimientos.length * 5} comparable fields match`
    : `FAIL — ${fixture}: ${diffs.length} diff(s) found`;

  return {
    fixture,
    passed,
    diffs,
    ignoredFields: Array.from(IGNORED_FIELDS),
    summary,
  };
}

/**
 * Formats a DiffReport as a human-readable string for console output.
 */
export function formatDiffReport(report: DiffReport): string {
  const lines: string[] = [`=== Round-Trip Report: ${report.fixture} ===`, report.summary, ''];

  if (report.passed) {
    lines.push('All comparable fields match.');
  } else {
    lines.push('DIFFS:');
    for (const diff of report.diffs) {
      const label =
        diff.status === 'mismatch'
          ? 'MISMATCH'
          : diff.status === 'missing_in_ours'
            ? 'MISSING IN OURS'
            : 'EXTRA IN OURS';
      lines.push(`  [${label}] ${diff.field}`);
      lines.push(`    Ours  : ${diff.ourValue ?? '(absent)'}`);
      lines.push(`    Theirs: ${diff.theirValue ?? '(absent)'}`);
    }
  }

  lines.push('');
  lines.push(`Ignored fields (${report.ignoredFields.length}): ${report.ignoredFields.join(', ')}`);

  return lines.join('\n');
}
